### ISSUE TITLE
Unhandled REPL handler exception processing message

### ISSUE THREAD

**Issue by NickeZ** [Olical/conjure#128]
Hello,

I get this backtrace when I connect with the conjure vim plugin to the nrepl server. Not sure if this is a problem in conjure or niddle.

Cross-posting https://github.com/pinealan/niddle/issues/2 since I don't know the root cause.

```
nREPL server started on port 32913 on host localhost - nrepl://localhost:32913
(ns conjure.internal (:require [clojure.pprint :as pp]))
ERROR: Unhandled REPL handler exception processing message {:code #?(:clj 'clj :cljs 'cljs :cljr 'cljr :default 'unknown), :id 3a319bc2-0aea-43ab-b825-a09bc01078e7, :op eval, :session 37f307d0-e15a-447f-ba0a-b51029447431}
java.lang.RuntimeException: Conditional read not allowed
        at clojure.lang.Util.runtimeException(Util.java:221)
        at clojure.lang.LispReader$ConditionalReader.checkConditionalAllowed(LispReader.java:1623)
        at clojure.lang.LispReader$ConditionalReader.invoke(LispReader.java:1627)
        at clojure.lang.LispReader$DispatchReader.invoke(LispReader.java:853)
        at clojure.lang.LispReader.read(LispReader.java:285)
        at clojure.lang.LispReader.read(LispReader.java:216)
        at clojure.lang.LispReader.read(LispReader.java:205)
        at clojure.lang.RT.readString(RT.java:1878)
        at clojure.lang.RT.readString(RT.java:1873)
        at clojure.core$read_string.invokeStatic(core.clj:3815)
        at clojure.core$read_string.invoke(core.clj:3805)
        at niddle.print$read_form.invokeStatic(print.clj:79)
        at niddle.print$read_form.invoke(print.clj:79)
        at niddle.print$printable_form.invokeStatic(print.clj:88)
        at niddle.print$printable_form.invoke(print.clj:87)
        at niddle.print$eval3892$fn__3894.invoke(print.clj:92)
        at clojure.lang.MultiFn.invoke(MultiFn.java:229)
        at niddle.print$niddle_mw$fn__3914.invoke(print.clj:126)
        at nrepl.middleware$wrap_conj_descriptor$fn__658.invoke(middleware.clj:16)
        at nrepl.middleware.caught$wrap_caught$fn__926.invoke(caught.clj:97)
        at nrepl.middleware$wrap_conj_descriptor$fn__658.invoke(middleware.clj:16)
        at nrepl.middleware.print$wrap_print$fn__893.invoke(print.clj:234)
        at nrepl.middleware$wrap_conj_descriptor$fn__658.invoke(middleware.clj:16)
        at nrepl.server$default_handler$fn__1586.invoke(server.clj:130)
        at nrepl.server$handle_STAR_.invokeStatic(server.clj:22)
        at nrepl.server$handle_STAR_.invoke(server.clj:19)
        at nrepl.server$handle$fn__1557.invoke(server.clj:39)
        at clojure.core$binding_conveyor_fn$fn__5754.invoke(core.clj:2030)
        at clojure.lang.AFn.call(AFn.java:18)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
        at java.base/java.lang.Thread.run(Thread.java:832)
conjure.internal=> nil
```

**Comment by Olical** [comment]
This looks like the nREPL you started doesn't support reader conditionals, so if niddle is parsing Clojure it's doing so without reader conditionals. I'd argue that it'd be a good thing to allow in that middleware, I don't think there's any way I can get around this from my end I'm afraid.

**Comment by NickeZ** [comment]
I'm not that well-versed in clojure yet, so this is probably a niddle problem?

**Comment by Olical** [comment]
That's okay, I think it's a bug in niddle though, [this line](https://github.com/pinealan/niddle/blob/master/src/niddle/print.clj#L79) should probably look like this.

```clojure
(defn read-form [code] (if (string? code) (read-string code {:read-cond :allow}) code))
```

**Comment by Olical** [comment]
Created a PR to fix it here https://github.com/pinealan/niddle/pull/3

You can rely on my fork through `deps.edn` if you need as well.

**Comment by Olical** [comment]
My PR is merged :slightly_smiling_face:
