### ISSUE TITLE
Error when trying to use Hy REPL: module 'hy' has no attribute 'repr'

### ISSUE THREAD

**Issue by ckp95** [Olical/conjure#354]
When I try to use the Hy REPL inside Conjure, I get this error straight away:

```
; "hy --repl-output-fn=hy.repr" (started)
; (err) Traceback (most recent call last):
; (err)   File "/tmp/hytest/.venv/bin/hy", line 8, in <module>
; (err)     sys.exit(hy_main())
; (err)   File "/tmp/hytest/.venv/lib/python3.8/site-packages/hy/cmdline.py", line 662, in hy_main
; (err)     sys.exit(cmdline_handler("hy", sys.argv))
; (err)   File "/tmp/hytest/.venv/lib/python3.8/site-packages/hy/cmdline.py", line 653, in cmdline_handler
; (err)     return run_repl(
; (err)   File "/tmp/hytest/.venv/lib/python3.8/site-packages/hy/cmdline.py", line 442, in run_repl
; (err)     hr = HyREPL(**kwargs)
; (err)   File "/tmp/hytest/.venv/lib/python3.8/site-packages/hy/cmdline.py", line 270, in __init__
; (err)     self.output_fn = getattr(importlib.import_module(module), f)
; (err) AttributeError: module 'hy' has no attribute 'repr'
; process exited with code 1
; --------------------------------------------------------------------------------
; "hy --repl-output-fn=hy.repr" (stopped)
```

I'm using Python 3.8.12, Hy 0.20.0, and the [vim-hy](https://github.com/hylang/vim-hy) plugin.

**Comment by Olical** [comment]
Nice!
