### ISSUE TITLE
Unable to compile conjure

### ISSUE THREAD

**Issue by devinalvaro** [Olical/conjure#74]
Recently I reinstalled my whole system, and got this error on Conjure's post install (`bin/compile`). I think this probably has something to do with dependencies, because on my old system it worked fine, but I can't figure out what's missing now. Could you help me figure this out, thank you!

```
[Conjure] Compiling Clojure...
Exception in thread "main" java.io.FileNotFoundException: -Sforce (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileInputStream.<init>(FileInputStream.java:93)
	at clojure.lang.Compiler.loadFile(Compiler.java:7314)
	at clojure.main$load_script.invokeStatic(main.clj:275)
	at clojure.main$script_opt.invokeStatic(main.clj:335)
	at clojure.main$script_opt.invoke(main.clj:330)
	at clojure.main$main.invokeStatic(main.clj:421)
	at clojure.main$main.doInvoke(main.clj:384)
	at clojure.lang.RestFn.invoke(RestFn.java:457)
	at clojure.lang.Var.invoke(Var.java:394)
	at clojure.lang.AFn.applyToHelper(AFn.java:165)
	at clojure.lang.Var.applyTo(Var.java:700)
	at clojure.main.main(main.java:37)
```

**Comment by Olical** [comment]
This smells like your `clojure` program in your system isn't the Clojure CLI as described here: https://clojure.org/guides/deps_and_cli

What happens if you just run `clojure` in your shell?

**Comment by Olical** [comment]
(alternatively, it is the CLI but an old version that doesn't support `-Sforce`?)

**Comment by devinalvaro** [comment]
Oh, turns out `clojure` from the package manager is too old (1.8.0), installed the 1.10.0 version and it works fine now. It surprised me that even the latest Fedora ships an outdated version of Clojure.

Thanks for your help!

**Comment by Olical** [comment]
Yay! Glad it's sorted! :tada:
